### ISSUE TITLE
attribute file change not detected

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#10]
Similar to previous versions the attribute file being updating is not always picked up and you must restart the program for it to refresh. Seems to happen when theirs an extended delay between matches.

**Comment by majikat768** [comment]
That is interesting, I haven't personally had that issue but I'll look into it.
I believe in the current release I did add a Reload button in the main window view.  Does that also not refresh the info?

**Comment by JSKoenig** [comment]
It didn't seem to help. Maybe windows is timing something out

**Comment by majikat768** [comment]
I actually was able to find the issue, I should hopefully be able to get that sorted out pretty quick.

**Comment by majikat768** [comment]
So the new release should hopefully fix this problem, I wasn't really able to test it since I hadn't encountered the problem...but it should try to reread the file now instead of just halting.

**Comment by JSKoenig** [comment]
Solved!
