### ISSUE TITLE
player "combat" log

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#11]
Inclusion of player names can make combat details harder to read.

![image](https://user-images.githubusercontent.com/41165269/197677631-416343f5-d361-443e-888e-1c6f939d6db0.png)

Could be changed to something like this.

![000239](https://user-images.githubusercontent.com/41165269/197678658-18f42919-fc2b-4977-a04e-9cdcc416bd60.png)

**Comment by majikat768** [comment]
Agreed, I've been looking into other ways to display this information.  Thanks!
