### ISSUE TITLE
File not found assets/json/spawn_points.json 

### ISSUE THREAD

**Issue by ismenc** [majikat768/HuntStatsLogger#13]
When i try to run main.py i get filenotfound error.
Maybe it needs to be uploaded to repo?

**Comment by majikat768** [comment]
Oops, you're right- I have json/ in the gitignore file but it shouldn't be. Thanks! I'll get that fixed.

**Comment by majikat768** [comment]
Should be fixed with the latest commit.

**Comment by ismenc** [comment]
> Should be fixed with the latest commit.

Confirmed. Thanks ♥
