### ISSUE TITLE
Ruler deleted after switching map and not created again

### ISSUE THREAD

**Issue by ismenc** [majikat768/HuntStatsLogger#14]
Hey! I'm testing the app after the json files were added. Congrats! **The app is brilliant!** and a great work
I will frecuently use it, report issues, give suggestions and try to participate if i can.

Here's a small bug:
Ruler is deleted after switching map
1. Ruler works fine on the map opened by default (desalle).
2. As you switch to other map Ruler object gets deleted, even if it's not activated
3. Ruler is not ever created again. `RuntimeError: wrapped C/C++ object of type Ruler has been deleted`

**Comment by majikat768** [comment]
Thanks!
Yeah, looks like the ruler object is only added on the window's initialization, but when switching maps, the whole Scene gets cleared and repopulated but I never added back the ruler.  Should be an easy fix.
