### ISSUE TITLE
More compact window option?

### ISSUE THREAD

**Issue by ZaHecc** [majikat768/HuntStatsLogger#22]
The window takes up most of my screen on 1080p so I was wondering if it was possible to make it a more compact window

**Comment by majikat768** [comment]
The window is resizeable, but there is currently a minimum allowable size for the window based on the window's contents...I will look into making this more customizable.
Thanks!

**Comment by majikat768** [comment]
I've pushed a quick fix to the repository, the window can now be minimized much smaller, and the main content area becomes scrollable.  I'll update the .exe momentarily.
