### ISSUE TITLE
App crash on launch due to invalid os release when launching on Linux based OS

### ISSUE THREAD

**Issue by Skerilyo** [majikat768/HuntStatsLogger#23]
`Traceback (most recent call last):
  File "/home/kali/HuntStatsLogger/./src/main.py", line 15, in <module>
    if int(platform.release()) >= 8:
ValueError: invalid literal for int() with base 10: '5.19.0-kali2-amd64'`

**Comment by majikat768** [comment]
Thanks!
I don't imagine most users generally run Hunt on Linux, so I pretty much developed it just with Windows in mind...
Also, that line of code generally is to make sure that the line charts appear the same regardless of screen size or resolution, so it should still work fine even if that line gets skipped.

**Comment by Skerilyo** [comment]
Oh you're right, it's just that I dev on Linux most of the time (so I couldn't launch your app on my work computer)

**Comment by majikat768** [comment]
Yeah, I had encountered a similar problem on my linux laptop a few times.
