### ISSUE TITLE
Still not a 100% sure on how to download this...

### ISSUE THREAD

**Issue by CrowFromTheGame** [majikat768/HuntStatsLogger#25]
Im not a tech guy and im still having trouble figuring out how to download and get this running. Could you make a video or something to make it more clear on what I have to do. Thanks.

**Comment by majikat768** [comment]
No problem!
So you have two options...the simplest is to go to the latest version on the Releases page, here:
https://github.com/majikat768/HuntStatsLogger/releases/tag/v0.4.2
and download either of the HuntStatsLogger.rar files.  You'll need something like winrar ( https://www.win-rar.com/start.html ) to open it.  Extract HuntStatsLogger.exe from the .rar file to your desktop, then you can just open it by double clicking HuntStatsLogger.exe.

However, sometimes Windows incorrectly thinks my program is a virus, and won't let you open it.  I believe it's possible to add an exception in your firewall or Windows Defender, I'd recommend looking up on google how to do this.

Your other option is just running it as a python script... to do this you'll need to download and install python:  https://www.python.org/downloads/
When installing, there'll be an option saying something like, "add Python to system PATH".  make sure that's checked.

Then you'll download my entire code repository; from the main page ( https://github.com/majikat768/HuntStatsLogger ) click on the box on the top right that says 'Code', and click Download Zip.  Extract the zip file to some folder, then in the folder, you'll need to run the start.ps1 file...sometimes, just double clicking this will work.  But you may need to right click it, and tell it to run with Windows Powershell.

Let me know if you need more assistance.

**Comment by CrowFromTheGame** [comment]
Ok, I tried to open it with WINrar but It only worked once. Then I tried the python download and I went through the steps and then it just kept crashing or not allowing me to use the file but every time I opened the start.ps1 file it opens the powershell terminal the disappears immediately.

**Comment by majikat768** [comment]
Interesting- so when you open it with WinRar, do you click on "Extract to..." and choose to put the .exe on the Desktop?  After that, you'll start it by opening the HuntStatsLogger.exe file.

Also, I just figured out the issue with python!  I'll push a change asap, but basically, if you open start.ps1 in notepad, remove the # from the first line, so it just says "pip install -r requirements.txt" and try again.

If there are still issues, try right clicking in the folder that start.ps1 is in, and choose Powershell > open Powershell Here.  Then type start.ps1 into the console window and click enter.  If it doesn't work, an error message should display, that should be helpful.

**Comment by CrowFromTheGame** [comment]
![Screenshot (364)](https://user-images.githubusercontent.com/118079758/201500578-5daea4fb-bd46-4a6e-8ee7-8c3b0dc95f7e.png)

**Comment by majikat768** [comment]
Hmm, you're sure you downloaded and extracted the entire code directory?  It should contain all of the files listed in the repository:
https://github.com/majikat768/HuntStatsLogger
, including requirements.txt.

**Comment by majikat768** [comment]
Directory should look like this when you execute start.ps1:

<img width="632" alt="Screenshot 2022-11-12 181144" src="https://user-images.githubusercontent.com/14895005/201500804-df13cb5f-51e6-4ced-badc-70a4aa742b79.png">

**Comment by CrowFromTheGame** [comment]
How do I change the resolution (I don't have a second monitor)

**Comment by CrowFromTheGame** [comment]
![Screenshot (365)](https://user-images.githubusercontent.com/118079758/201500921-ac5cd88b-4fd0-4b0f-92cd-b08c7f1499ba.png)

**Comment by majikat768** [comment]
ahh, that may be an issue, you're the second person who's mentioned the window being too large.  Unfortunately it's not resizable currently, but I'll work on getting that fixed asap!

**Comment by majikat768** [comment]
Just for reference, what is the resolution of your screen currently?

**Comment by CrowFromTheGame** [comment]
1920x1080

**Comment by majikat768** [comment]
I've pushed a quick fix, so that the window can be resized, and the main content area is scrollable.

**Comment by CrowFromTheGame** [comment]
So do I just reinstall the software?

**Comment by CrowFromTheGame** [comment]
Also mmr not showing up properly
![Screenshot (366)](https://user-images.githubusercontent.com/118079758/201538497-17b46fdf-e4e8-4095-8dc6-deb8370175b6.png)

**Comment by majikat768** [comment]
In settings you'll need to set your steam username before your MMR will show up.
After you set your username in settings, exit the program then restart, then it should work.
