### ISSUE TITLE
New Map size gives false ruler length

### ISSUE THREAD

**Issue by Skerilyo** [majikat768/HuntStatsLogger#29]
![image](https://user-images.githubusercontent.com/41216545/202860121-fe3fa77d-4ad6-4975-a3ec-36147f9a7a65.png)
Based on https://hunt-map.info/

![image](https://user-images.githubusercontent.com/41216545/202860157-9edf4fa3-fba1-4a4c-9d4e-047a587bf987.png)
Based on this tool

Seems like the map has been reduced by half, but ruler length didn't follow

**Comment by majikat768** [comment]
Oh, you're right! That should be an easy fix, thanks.

**Comment by majikat768** [comment]
Fixed in latest commit.  Also noticed that the coordinates under the mouse were incorrect in the status bar, so that's fixed as well.
