### ISSUE TITLE
Error on parsing 'blood_line_name'

### ISSUE THREAD

**Issue by Geograph-us** [majikat768/HuntStatsLogger#3]
Сaught an error when parsing attributes.xml (attached):

> building json object
> Traceback (most recent call last):
>   File "settings\Logger.py", line 52, in run
>   File "resources.py", line 256, in generate_checksum
>     "blood_line_name":hunter["blood_line_name"],
> KeyError: 'blood_line_name'

I think it's because empty value in line 1902 xml-file:

`<Attr name="MissionBagPlayer_1_2_blood_line_name" value=""/>`

[attributes.xml.txt](https://github.com/majikat768/HuntStatsLogger/files/9281554/attributes.xml.txt)

**Comment by majikat768** [comment]
That is the issue, currently it just ignored rows where value="", so blood_line_name just gets ignored...for now I can update it so any value that is empty will be reassigned to some placeholder, which hopefully will prevent that error from showing up.
