### ISSUE TITLE
Predicted MMR change isn't the same in graph and in main window

### ISSUE THREAD

**Issue by Skerilyo** [majikat768/HuntStatsLogger#30]
![image](https://user-images.githubusercontent.com/41216545/202860279-44ce33f0-7dcf-4ee6-9419-eef35e46727c.png)

![image](https://user-images.githubusercontent.com/41216545/202860295-1863de1e-1be3-4fb3-9ead-86490416a568.png)

The calculation of the chart mmr seems only based on the latest game "tendency" in mmr, whereas the calculation in the main windows seems to be based on the mmr of people that killed me

**Comment by Skerilyo** [comment]
Ah, after launching the executable again, it updated the graph mmr prediction to match the main window one

**Comment by majikat768** [comment]
I had noticed that, particularly after it loads new data after a hunt, sometimes it shows two different values...although it should be using the same function for both, so I'll have to look into what's going on there.

**Comment by Skerilyo** [comment]
![image](https://user-images.githubusercontent.com/41216545/202920828-6e268780-3763-455e-9a37-0cbf1fa96379.png)
Seems like it's not updating at all through the usage of the tool, the mmr exceptations in the chart are the one from 6-7 games ago

**Comment by majikat768** [comment]
Just pushed a commit with the fix for this bug.
