### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by mrskizzex** [majikat768/HuntStatsLogger#32]
So after running the program for 14h it seems that it's hung on something in the background because it uses around 12% of cpu which is quite a lot. I'll switch to console version and run it some more to maybe see what's going on.
![image](https://user-images.githubusercontent.com/11503128/204041032-3d5f6f3c-2e4f-4a8b-b384-a414a1f36274.png)
![image](https://user-images.githubusercontent.com/11503128/204041074-f983825e-d415-46cd-99c6-54892418cb23.png)

**Comment by mrskizzex** [comment]
Nvm, I figured it out. If Hunt install folder changes, app still tries to read old location in a loop resulting in high CPU usage.

**Comment by Skerilyo** [comment]
I mean, could be a good idea to make it so it doesn't try in a loop and instead checks one time if the wanted file is present, and just raised an error if it is not x)

**Comment by majikat768** [comment]
That is good to know. Should be pretty easy to fix.  Thanks!
