### ISSUE TITLE
Update 1.11 

### ISSUE THREAD

**Issue by nbergman** [majikat768/HuntStatsLogger#34]
After Hunt: Showdown update 1.11 on Dec 7th the program is no longer analyzing the after match file attribute to refresh the UI data. 

Hunt V 1.2555

Please let me know if any further information is needed.

- BergieGaming

**Comment by majikat768** [comment]
I just noticed that as well, they've made a couple changes to the generated attributes file, which breaks it....
I think this should be a fairly easy fix.

Thanks!

**Comment by nbergman** [comment]
Perfect! Let me know if you need anything to assist.

**Comment by majikat768** [comment]
Just pushed a commit that should address this issue, I'm gonna be testing it for a while and hopefully be able to get a new build out soon.

**Comment by nbergman** [comment]
If you're open for additional QA feedback. I'm willing to assist if you can provide a separate QA/UAT build.
