### ISSUE TITLE
[Feature] Keeping track of progress after a steam name change

### ISSUE THREAD

**Issue by gregtofu** [majikat768/HuntStatsLogger#37]
Everything is in the title. 
I do not know whether this is already a feature yet, but just in case : 

My current steam name is REPENT; if I wanted to change it back to my regular steam name, i'd like my stats to keep being tracked as if nothing had changed - after all, I change steam aliases very often. 

Same goes for my regular teammates, although I can't think of a way that wouldn't require a manual input.

**Comment by majikat768** [comment]
I believe this is partially implemented, but I haven't really tested it fully yet....each hunter has an associated profileid, which remains the same regardless of their steam name.  It's probably inconsistent right now, some of the data is tracked by the hunter's profileid, and some is by the steam name.  Your KDA at least should remain the same throughout, but the data in the MMR charts may be different once you change it....So I'll work on that!

**Comment by majikat768** [comment]
I made some updates in the latest code commit, so more of the data is tracked by profile id instead of steam name, and it appears to be working so far...so hopefully all data will persist through changing one's steam name now.
