### ISSUE TITLE
[Feature] Regular teammates stats

### ISSUE THREAD

**Issue by gregtofu** [majikat768/HuntStatsLogger#38]
Would be nice to be able to keep track of your regular teammate's stats as well as yours so you can see how the group MMR evolves over time and who's having a hard time or whatever.

**Comment by majikat768** [comment]
I like this idea!
I just pushed an update to the repository with a new tab which tracks the MMR of your most frequent teams and team members.  still a work in progress, but I'll try to get a build of it up soon as well.
