### ISSUE TITLE
Tracker stopped tracking games

### ISSUE THREAD

**Issue by CrowFromTheGame** [majikat768/HuntStatsLogger#40]
I have gotten to at least 322 games and now that tracker has stopped updating the graph and match replays. It still changes the level, kda, and mmr but not the games.
![Screenshot (378)](https://user-images.githubusercontent.com/118079758/206806547-e1faccf5-5f97-4ad0-ad5a-9fc200229590.png)

**Comment by majikat768** [comment]
What JSkoenig said, this is due to the recent Hunt patch update. Its fixed in the repository, but I'll get a fixed build posted very soon.
