### ISSUE TITLE
MMR ist Not plotted

### ISSUE THREAD

**Issue by Laser-0** [majikat768/HuntStatsLogger#43]
Since some Versions the MMR ist displayed as -1 and the chart ist empty.

**Comment by majikat768** [comment]
Are you running it as a python script, or the .exe from the releases?  Is this after updating your username under settings?
It should be working fine in the code repository, and I'll be pushing some new code and also a new build soon that should fix a couple bugs.

**Comment by Laser-0** [comment]
I am running it as a python script. I just updated to the new version and the MMR is displayed correctly. Thanks for your help.
