### ISSUE TITLE
MMR not showing correct value

### ISSUE THREAD

**Issue by madmax01** [majikat768/HuntStatsLogger#49]
Hi team,

When using the App it always show up  MMR: -1    and Best: -1

When checking the attribute file it shows always an Value

Can this please be fixed

**Comment by majikat768** [comment]
Did you set the correct hunt directory, and also set your steam username?

**Comment by madmax01** [comment]
ahhh. missed the "Steam Name" Part... sry ;).... very nice tool ;)
