### ISSUE TITLE
New issues with 1.12

### ISSUE THREAD

**Issue by majikat768** [majikat768/HuntStatsLogger#50]
there's at least one new attribute added with the last update:
`<Attr name="MissionBagAddNoBloodlineXp" value="false"/>`
which the table doesn't recognize, so it's not recording hunts.

will be an easy fix, also should be able to set the app to ignore fields it doesn't recognize, instead of just failing.

**Comment by majikat768** [comment]
Another new field is `MissionBagIsTutorial`

**Comment by majikat768** [comment]
You're right, I just see the error I made; I'll have it fixed momentary :)  thanks!!

**Comment by majikat768** [comment]
Okay, it should work now.

**Comment by JSKoenig** [comment]
It's working again!

**Comment by majikat768** [comment]
sweet!  I'll get a new .exe build posted this afternoon too.
