### ISSUE TITLE
Not logging games anymore

### ISSUE THREAD

**Issue by CrowFromTheGame** [majikat768/HuntStatsLogger#51]
I changed my steam name to "Blood And Wine" and made sure to change the setting in the racker but its not tracking games anymore. I even tried installing the newest release.
![Screenshot (440)](https://user-images.githubusercontent.com/118079758/229012054-d2e25038-3669-420c-b965-4f669d726879.png)

**Comment by majikat768** [comment]
Indeed, this is due to some new data attributes being added in update 1.12:
https://github.com/majikat768/HuntStatsLogger/issues/50

I've made the necessary changes to the code, so it is fixed in the repository, and I'm going to try to get a new build uploaded by tomorrow.

**Comment by CrowFromTheGame** [comment]
Super cool. Thanks!
