### ISSUE TITLE
0.4.9 no update after round

### ISSUE THREAD

**Issue by Hrungdisaster** [majikat768/HuntStatsLogger#52]
Hi!

0.4.9 exe does note "File change detected", however does only display results after a restart of "HuntStatsLogger.exe" opposite to 0.4.8 and before.

Btw: Thanks for all the work you invest in this project! Exactly what my mates and me were locking for (with too less python ambition to do it ourselfs).

**Comment by CrowFromTheGame** [comment]
![Screenshot (441)](https://user-images.githubusercontent.com/118079758/229329073-5050352b-bcb8-44c8-b66d-ab32c30ded9c.png)

**Comment by majikat768** [comment]
I just noticed this as well, not completely sure what's causing that but I'll look into it.  Thanks!

**Comment by majikat768** [comment]
Think I've tracked it down, gonna do some testing and should be a fix up shortly.

**Comment by majikat768** [comment]
Fix is up!  Everything seems to be working now.

**Comment by Hrungdisaster** [comment]
Works fine, thanks!
