### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Unterrr** [majikat768/HuntStatsLogger#54]
Hello,

Yesterday it was working fine but today when I tried to open it I was hit with this error.
Cant seem to figure out whats causing it.

I added a screenshot of the complete error log.

Really like your program! Hope we can figure out whats causing this
![huntstatserror](https://user-images.githubusercontent.com/129314330/229347261-b44d8f05-80d3-421c-b018-ee15fa4347aa.png)

Kind regards

**Comment by majikat768** [comment]
I think this is maybe due to somebody having an unusual character in their steam name, and python is using a different character encoding so it doesn't understand it...I'll see what I can do to figure that out.

Thanks!

**Comment by majikat768** [comment]
I found the issue, should be fixed now in the code repository.  I'll try to get a new build with the fix posted this weekend too.

**Comment by Unterrr** [comment]
Nice!

In the mean time I just deleted the hutstats.db in %AppData%\Roaming\hsl_files2 and it started working like before again.
