### ISSUE TITLE
[Feature] Damage History

### ISSUE THREAD

**Issue by fscorrupt** [majikat768/HuntStatsLogger#55]
Hey, 

I would like to request a new feature to be added to the "tracker" tool. It would be great if you could incorporate the "damage history" that was introduced with 1.12 into the tracker. 
This feature would enable users to view and track damage history for any given item, providing valuable insights into the health and Damage of every round.

Thanks!

**Comment by majikat768** [comment]
I will look into it, I'm not sure if that's possible though, the only data we have access to is what's seen in the post-match screen...so I don't think the damage history is recorded locally. But I will find out!
