### ISSUE TITLE
MMR and Teams

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#56]
It'd be really nice if you could move the team with your steam name to always be at the top of a matches teams list. I think you broke the mmr  estimate because its always estimating a huge positive number after a match and then after the next match it shows the change as 0.

**Comment by JSKoenig** [comment]
After deleting my hsl_files2 folder the restarting the app and changing my steam name the app keeps crashing immediately on launch

**Comment by majikat768** [comment]
Hmm, I didn't make any changes to the MMR calculation for this change so that shouldn't be any different...and it should still be configured to have your own team at the top. I'll check it out and make sure I have the correct code uploaded.
Are you running the exe or with python?

**Comment by JSKoenig** [comment]
Python

**Comment by JSKoenig** [comment]
I just tried the 5.0 exe and and same thing happens as soon as i set my steam user name. 4.9 exe works fine

**Comment by majikat768** [comment]
Does the terminal output any error messages?
So far everything's still working fine for me, both in python and the .exe...I'll keep investigating though.
Does your steam name contain any unusual characters?  I have noticed odd behavior before when a player's username contains unicode symbols....

**Comment by majikat768** [comment]
I'm actually getting the same issue now.  strange.

**Comment by majikat768** [comment]
Okay I think I've figured out where the issue is....should be able to have a fix up soon.
Thanks!!

**Comment by JSKoenig** [comment]
Awesome!

**Comment by majikat768** [comment]
just pushed some code that hopefully should fix it...I believe the problem was in playing either quickplay or as a solo, seemed to break how the team sections are laid out.
