### ISSUE TITLE
[Crash] After lobbies it crashes

### ISSUE THREAD

**Issue by RzR332Guyver** [majikat768/HuntStatsLogger#57]
The logger seems to, at least for me, in the latest update, crash after getting back to lobby.
I don't know if it's because I tried to bring the window up IMMEDIATELY after I pressed "continue" and got back to the roster-screen, or what but it would just toss out that windows prompt of "program not responding" or whatever and then immediately die.

Unsure how to really test it, though and it doesn't seem to have given an error of sorts. I was using the latest 0.5.0 version.

**Comment by majikat768** [comment]
This may be the same bug reported in https://github.com/majikat768/HuntStatsLogger/issues/56.  I believe the issues been resolved in the code, so if you're running it in python it should work, and I'll get a new .exe posted soon. In the meantime using the previous build should still work.
Thanks!

**Comment by majikat768** [comment]
Just uploaded the fixed version.
