### ISSUE TITLE
[Feature Request] Auto-start Logger on launch

### ISSUE THREAD

**Issue by davefatkin** [majikat768/HuntStatsLogger#6]
Once you're set up HSL, it would be really helpful if the Logger automatically started when you launch the program. I've certainly forgotten to turn it on and have missed out on tracking matches.

**Comment by majikat768** [comment]
I was thinking the same!  From the perspective of putting it together, it's useful to be able to toggle it on and off, which is why I had it set up that way.  But I can definitely make it start logging automatically.
Thanks!

**Comment by majikat768** [comment]
For now I've added a checkbox option in settings which will make it start logging on it's own when it launches, it's in the newest release.
In the future I plan to make automatically logging the default.

**Comment by davefatkin** [comment]
Thanks, @majikat768!
