### ISSUE TITLE
majority of matches are logged as victories post 1.13

### ISSUE THREAD

**Issue by 3MT** [majikat768/HuntStatsLogger#64]
I'm not sure what the pattern is but the vast majority of my games are shown as victories.
It might be due to death cheat? Looking at my history I believe every incorrect victory is a match I had active death cheat.

![image](https://github.com/majikat768/HuntStatsLogger/assets/6055934/6e6f18a4-a3a2-4e91-9a91-cb1aa9e52a77)

As you can see in this case our team does not successfully extract but the match is marked a win.

Thanks, appreciate the tool it's excellent.

**Comment by majikat768** [comment]
Oh interesting, I think i see why...there's a property called "IsHunterDead", but there's another one called "WasDeathlessUsed", so they'll need to be compared to get it right.  That should be a pretty easy fix-- thanks!
