### ISSUE TITLE
My Teams listdont show anything

### ISSUE THREAD

**Issue by Rick45** [majikat768/HuntStatsLogger#65]
Hi,
The when  the number of  My teams is too big it stop to show them at all. currently if i do a calculate teams it removes them all from the .ini file.

if i manually re-add the  config to the my teams it shows them without any issue.

`my_teams="[[17179895197, 64424601093, 68719589625], [17179895197, 68719589625], [17179895197, 51539655225, 64424601093], [17179895197, 64424810299, 68719589625]]"
`

 no error trow in the IDE only this message.

`requested query: select 'hunters_view'.profileid,'hunters_view'.game_id, 'hunters_view'.timestamp, 'teams'.team_num from 'hunters_view' join 'teams_view' on (ownteam = 'true' and 'hunters_view'.game_id = 'teams_view'.game_id and 'hunters_view'.team_num = 'teams_view'.team_num) join 'games_view' on ('games_view'.MissionBagIsQuickPlay = 'false' and 'teams_view'.game_id = 'games_view'.game_id) where 'hunters_view'.timestamp = 1683671974
no such column: teams.team_num
`

attached my database. 

[huntstats.zip](https://github.com/majikat768/HuntStatsLogger/files/11961923/huntstats.zip)

eddit: updated the title

**Comment by Rick45** [comment]
@majikat768 in the GetTeamMembers method the query have 

`"select 'hunters_view'.profileid,'hunters_view'.game_id, 'hunters_view'.timestamp, 'teams'.team_num from 'hunters_view' ....`

i replaced the ` 'teams'.team_num` with `'hunters_view'.team_num ` and now is working without any issue.

this makes sense?

**Comment by majikat768** [comment]
Ahh that does make sense!  If you wanna do a pull request I'll approve it, otherwise I can make those changes in a little bit.
Thanks!

**Comment by majikat768** [comment]
Thanks!
